spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  shardingsphere:
    datasource:
      names: ds-master,ds-slave1,ds-slave2
      # 配置主库
      ds-master:
        jdbc-url: jdbc:mysql://47.108.175.249:53306/gmh_test1?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=Hongkong
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        username: gmh_test1
        password: FW3Yc6si3kae3eCs
        #最大连接数
        maxPoolSize: 20
      ds-slave1: # 配置第一个从库
        jdbc-url: jdbc:mysql://47.108.175.249:53306/gmh_test1?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=Hongkong
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        username: gmh_test1
        password: FW3Yc6si3kae3eCs
        maxPoolSize: 20
      ds-slave2: # 配置第二个从库
        jdbc-url: jdbc:mysql://47.108.175.249:53306/gmh_test2?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=Hongkong
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        username: gmh_test2
        password: 3p8HEmJ635snw2ZH
        maxPoolSize: 20

    masterslave:
      load-balance-algorithm-type: round_robin #从库负载均衡算法类型，可选值：ROUND_ROBIN，RANDOM。若`loadBalanceAlgorithmClassName`存在则忽略该配置
      name: ms
      master-data-source-name: ds-master #主库数据源名称
      slave-data-source-names: ds-slave1,ds-slave2 #从库数据源名称列表
    props:
      sql.show: true # 开启SQL显示，默认值: false，注意：仅配置读写分离时不会打印日志！！！
      executor.size: 2 #工作线程数量，默认值: CPU核数