CREATE TABLE `gmh_order_2022_8` (
  `id` bigint NOT NULL COMMENT '订单Id',
  `order_number` int NOT NULL COMMENT '订单编号',
  `order_code` varchar(255) DEFAULT NULL COMMENT '自提码or券码编号',
  `user_id` int DEFAULT NULL COMMENT '用户Id',
  `user_nickname` varchar(255) DEFAULT NULL COMMENT '用户昵称',
  `order_type_id` int DEFAULT NULL COMMENT '订单类型Id',
  `order_type_name` varchar(255) DEFAULT NULL COMMENT '订单类型名称',
  `prepayed_pay_money` decimal(10,2) DEFAULT NULL COMMENT '预付金额',
  `real_pay_money` decimal(10,2) DEFAULT NULL COMMENT '实付金额',
  `pay_method_id` int DEFAULT NULL COMMENT '支付方式Id',
  `pay_method_name` varchar(255) DEFAULT NULL COMMENT '支付方式名称',
  `order_status_id` int DEFAULT NULL COMMENT '订单状态ID',
  `order_status_name` varchar(255) DEFAULT NULL COMMENT '订单状态名称',
  `order_time` datetime DEFAULT NULL COMMENT '下单时间',
  `delivery_method` varchar(255) DEFAULT NULL COMMENT '配送方式',
  `order_total_money` decimal(10,2) DEFAULT NULL COMMENT '订单总金额',
  `coupon_money` decimal(10,2) DEFAULT NULL COMMENT '折扣券金额',
  `freight` decimal(10,2) DEFAULT NULL COMMENT '运费费用',
  `red_envelope_money` decimal(10,2) DEFAULT NULL COMMENT '预计赚取红包金额',
  `receiver_person_name` varchar(255) DEFAULT NULL COMMENT '收货人姓名',
  `receiver_person_phone` varchar(255) DEFAULT NULL COMMENT '收货人电话',
  `receive_perosn_address` varchar(255) DEFAULT NULL COMMENT '收货人地址',
  `receive_perosn_address_details` varchar(255) DEFAULT NULL COMMENT '收货人详细地址',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci AVG_ROW_LENGTH=32 COMMENT='订单宽表'
--
CREATE TABLE `gmh_product_2022_10` (
  `id` bigint NOT NULL COMMENT 'id',
  `product_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '商品名称',
  `cate_id` bigint DEFAULT NULL COMMENT '该商品的分类(gmh_commodity_category表)id',
  `commodity_category_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '商品类目名',
  `p_cate_id` int DEFAULT NULL COMMENT '该商品的上级分类(gmh_commodity_category表)id',
  `product_specs_id` int DEFAULT NULL COMMENT '产品规格',
  `product_introduction` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '商品描述',
  `status` tinyint DEFAULT '0' COMMENT '商品状态 0待审核  1已通过（上架中）2 已下架  3 已驳回',
  `is_delete` tinyint DEFAULT '0' COMMENT '是否删除 0 未删除  1 已删除（必须在下架状态才能删除）',
  `color` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '颜色',
  `specs_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '型号',
  `product_specs` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '产品规格',
  `cover_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '产品主图',
  `slider_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '轮播图',
  `product_price` decimal(10,2) DEFAULT NULL COMMENT '商品售价',
  `product_market_price` decimal(10,2) DEFAULT NULL COMMENT '商品市场价',
  `product_settlement_price` decimal(10,2) DEFAULT NULL COMMENT '商品结算价',
  `discount` decimal(10,2) DEFAULT NULL COMMENT '折扣比例',
  `stock` int DEFAULT NULL COMMENT '库存',
  `sales` int DEFAULT '0' COMMENT '已有销量',
  `virtual_sales_amount` int DEFAULT NULL COMMENT '商品虚拟销售数量',
  `real_sales_amount` int DEFAULT NULL COMMENT '商品真实销售数量',
  `share_images` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '分享图片',
  `share_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '分享标题',
  `shopId` int DEFAULT NULL COMMENT '关联的商铺的id(gmh_shop)',
  `shop_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '商铺名称',
  `shop_mobile` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '商店联系电话',
  `business_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '营业时间',
  `shop_intro` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '商铺简介',
  `shop_adress` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '商铺地址',
  `shop_lng` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '商铺经度',
  `shop_lat` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '商铺纬度',
  `legal_person` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '法人',
  `id_card` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '身份证号码',
  `current_residence_adress` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '现居住地址',
  `mobile_phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '法人联系电话',
  `id_card_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `business_license_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '营业执照图片地址',
  `qrcode` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '二维码',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='商品信息宽表'