spring:
  shardingsphere:
    #参数配置，显示sql
    props:
      sql:
        show: true
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://47.108.175.249:53306/gmh_test1?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false&rewriteBatchedStatements=true
        username: gmh_test1
        password: FW3Yc6si3kae3eCs
    #sharding
    sharding:
      tables:
        gmh_product:
          # actual-data-nodes: ds.gmh_order_$->{2020..2022}_$->{1..12}
          actual-data-nodes: ds.gmh_product_$->{2022..2022}_$->{01..12}
          table-strategy:
            standard:
              sharding-column: create_time
              precise-algorithm-class-name: com.gmh.mail.config.shardingjdbc.DatePreciseShardingAlgorithm
              range-algorithm-class-name: com.gmh.mail.config.shardingjdbc.DateRangeShardingAlgorithm

      binding-tables:
        - gmh_product
      defaultDataSourceName: ds



